export function getInstallGuide(origin: string) {
  const installer = `${new URL(origin).origin}/install.sh`;
  const powershellInstaller = `${new URL(origin).origin}/install.ps1`;

  return [
    "# Install and verify Jevia",
    "",
    "You are a coding agent helping set up Jevia, an outcome-aware model router. Work in the user's intended project directory. Follow these steps in order, inspect each result, and stop on failure. Do not claim success without observing it.",
    "",
    "## 1. Check prerequisites",
    "",
    "On macOS, Linux, or WSL, use a Bash-compatible terminal. On native Windows, use PowerShell 5.1 or newer. Both installers download a prebuilt binary and do not require Rust or Cargo. The shell installer requires curl and a SHA-256 utility; PowerShell uses its built-in web and checksum commands. Check the prerequisites for your platform:",
    "",
    "```bash",
    "curl --version",
    "command -v sha256sum || command -v shasum",
    "```",
    "",
    "```powershell",
    "$PSVersionTable.PSVersion",
    "```",
    "",
    "If a prerequisite is missing, explain the blocker and ask before installing it. Preserve existing project files and shell configuration.",
    "",
    "## 2. Install the CLI",
    "",
    `Review the shell installer at ${installer} or the Windows installer at ${powershellInstaller} before running it. The selected installer downloads the matching Jevia 0.1.7 binary from https://github.com/assistant-ui/jevia/releases/tag/v0.1.7, and verifies its SHA-256 checksum before installing it.`,
    "",
    "```bash",
    "set -euo pipefail",
    `curl -fsSL ${installer} | sh`,
    "jevia --version",
    "```",
    "",
    "On native Windows, run the equivalent PowerShell installer:",
    "",
    "```powershell",
    `irm ${powershellInstaller} | iex`,
    "jevia --version",
    "```",
    "",
    "Run only the installer for the current platform. Check the exit status of each command; stop if the download, checksum, install, or version check fails. If the URL uses localhost, that means the machine running these commands. Keep the development server running there, or ask for the deployed site URL when working on another machine. The default install directory is ~/.local/bin on macOS/Linux and LocalAppData\\Jevia\\bin on Windows. If Jevia is not on PATH, report the installer's PATH instruction; do not silently rewrite shell profiles or the Windows user PATH.",
    "",
    "## 3. Initialize the project",
    "",
    "From the intended project directory, create local policy only if it does not already exist:",
    "",
    "```bash",
    "if [ ! -f .jevia/config.toml ]; then",
    "  jevia init",
    "fi",
    "```",
    "",
    "Review .jevia/config.toml. Preserve existing policy, harness mappings, and local run history. Do not force initialization, replace configuration, or clear storage to make a check pass.",
    "",
    "## 4. Configure the Jev credential",
    "",
    "Jevia reads TYPESAFE_API_KEY from the environment. If it is already set, reuse it without printing it. Otherwise ask the user to set their real key locally, in the environment used for subsequent commands:",
    "",
    "```bash",
    'export TYPESAFE_API_KEY="your-key"',
    "```",
    "",
    "The value above is a placeholder, not a working credential. Never ask the user to paste a secret into chat, and never save it in this guide, project config, logs, or source control. Stop if a real key is not available.",
    "",
    "## 5. Verify local state and the live connection",
    "",
    "```bash",
    "jevia doctor",
    "jevia check",
    "```",
    "",
    "Run doctor first and proceed only if it exits successfully. It validates local configuration, storage, cache, and the presence of credentials without making an API request. Check then sends a live diagnostic task to Jev, which requires network access and may incur provider usage. Confirm the user permits this request before running it.",
    "",
    "A successful check exits with status 0 and prints `jev api: ok` followed by `jevia: ready`. It does not store a run or use a cached routing decision. If it fails, report the failing diagnostic and sanitized error; do not invent a successful response or silently change the provider endpoint.",
    "",
    "## 6. Route a sample task and inspect the record",
    "",
    "After check succeeds, and with the user's permission for another routing request and a local record, run:",
    "",
    "```bash",
    'jevia route --json "fix a typo in the README"',
    "jevia runs --json",
    "jevia cache status",
    "```",
    "",
    "Confirm the routing JSON contains a run ID, selected tier, and confidence; find that run in the local history. Report whether a fallback was applied. Routing chooses a tier; it does not execute the coding task or prove that the task succeeded. Do not record success feedback just because routing or installation worked.",
    "",
    "## 7. Report what was verified",
    "",
    "Summarize the installed Jevia version, project/config location, doctor and check exit results, the observed readiness message, and the sample run ID/tier if that step was authorized. Never include credentials. Separate completed checks from skipped or blocked steps and give the next action for any blocker.",
    "",
    "## Optional: run the automatic CLI pipeline",
    "",
    "Ask which installed harness and models the user wants, then run `jevia harness presets` to check for a built-in shell-free template. Presets cover Codex, Claude Code, OpenCode, and Gemini CLI but never guess model IDs, credentials, or permissions. Preview setup before applying it; do not overwrite an existing adapter. Check the installed version: passive observations and the opt-in verification default require CLI 0.1.6 or newer. CLI 0.1.4–0.1.5 enabled test discovery by default. Existing explicit verification remains enabled unless the user chooses to change it. Documentation and examples: https://github.com/assistant-ui/jevia/blob/main/docs/reference.md#harness-adapters.",
    "",
    "With the user's permission to execute the task, run `jevia run <configured-harness> <task>`. Jevia routes, launches the agent, and records lifecycle and execution facts automatically in the selected backend. No manual `feedback` or `runs complete` step is needed after `jevia run`. Since CLI 0.1.6, additional verification is opt-in and passive observations inform later routing even when the task outcome is unknown. Inspect `jevia runs --json` to report the actual evidence, not an assumed success.",
    "",
    "Optional verification happens when the launched process/session finishes, not after each agent message or tool call. A process exit or agent-reported completion is not proof of task success; do not fill this gap by submitting guessed feedback. Recording works for Python, Go, and mixed-language projects without extra tests. Jevia does not install an agent or test runner, supply credentials, bypass agent permission prompts, or automatically retry failed work. Passing tests is evidence, not proof of every requirement.",
    "CLI 0.1.6 native capture supports Claude Code 2.1.251+, tested Codex 0.158.x on macOS/Linux (with normal /hooks trust review), and OpenCode v1 >= 1.18.33. Unsupported versions and remote sessions keep process-level observations. Capture is best-effort and does not establish complete model attribution. Raw prompts, tool contents, and transcripts are not retained. Inspect execution.observations for coverage; back up history and upgrade to CLI 0.1.6 and SDK 0.1.2 together for schema 6. Do not promise these features if the installed CLI is older than 0.1.6.",
    "",
    "For route-only or SDK-controlled work outside `jevia run`, feedback and verification are optional. The application owns execution and may report a known outcome without a verifier; no human feedback prompt is required. Skipping feedback leaves the recorded outcome unknown. Later routes still use other eligible recorded outcomes automatically. These are separate integration choices, not extra steps after the automatic CLI pipeline. Details: https://github.com/assistant-ui/jevia/blob/main/docs/reference.md#automatic-cli-pipeline.",
    "",
  ].join("\n");
}
