export function getInstallGuide(origin: string) {
  const installer = `${new URL(origin).origin}/install.sh`;

  return [
    "# Install and verify Jevia",
    "",
    "You are a coding agent helping set up Jevia, an outcome-aware model router. Work in the user's intended project directory. Follow these steps in order, inspect each result, and stop on failure. Do not claim success without observing it.",
    "",
    "## 1. Check prerequisites",
    "",
    "Use a Bash-compatible terminal on macOS, Linux, or WSL. The installer downloads a prebuilt binary for Intel or ARM and does not require Rust or Cargo. It requires curl, a SHA-256 utility, and network access. Check what is already installed:",
    "",
    "```bash",
    "curl --version",
    "command -v sha256sum || command -v shasum",
    "```",
    "",
    "If a prerequisite is missing, explain the blocker and ask before installing it. Preserve existing project files and shell configuration.",
    "",
    "## 2. Install the CLI",
    "",
    `Review the installer at ${installer} before running it. It detects macOS or Linux and Intel or ARM, downloads the matching Jevia 0.1.3 binary from https://github.com/assistant-ui/jevia/releases/tag/v0.1.3, and verifies its SHA-256 checksum before installing it.`,
    "",
    "```bash",
    "set -euo pipefail",
    `curl -fsSL ${installer} | sh`,
    "jevia --version",
    "```",
    "",
    "Check the exit status of each command; stop if the download, checksum, install, or version check fails. If the URL uses localhost, that means the machine running these commands. Keep the development server running there, or ask for the deployed site URL when working on another machine. The default install directory is ~/.local/bin. If Jevia is not on PATH, report the installer's PATH instruction; do not silently rewrite shell profiles.",
    "",
    "## 3. Initialize the project",
    "",
    "From the intended project directory, create local policy only if it does not already exist:",
    "",
    "```bash",
    "if [ ! -f .jevia/config.toml ]; then",
    "  jevia init",
    "fi",
    "```",
    "",
    "Review .jevia/config.toml. Preserve existing policy, harness mappings, and local run history. Do not force initialization, replace configuration, or clear storage to make a check pass.",
    "",
    "## 4. Configure the Jev credential",
    "",
    "Jevia reads TYPESAFE_API_KEY from the environment. If it is already set, reuse it without printing it. Otherwise ask the user to set their real key locally, in the environment used for subsequent commands:",
    "",
    "```bash",
    'export TYPESAFE_API_KEY="your-key"',
    "```",
    "",
    "The value above is a placeholder, not a working credential. Never ask the user to paste a secret into chat, and never save it in this guide, project config, logs, or source control. Stop if a real key is not available.",
    "",
    "## 5. Verify local state and the live connection",
    "",
    "```bash",
    "jevia doctor",
    "jevia check",
    "```",
    "",
    "Run doctor first and proceed only if it exits successfully. It validates local configuration, storage, cache, and the presence of credentials without making an API request. Check then sends a live diagnostic task to Jev, which requires network access and may incur provider usage. Confirm the user permits this request before running it.",
    "",
    "A successful check exits with status 0 and prints `jev api: ok` followed by `jevia: ready`. It does not store a run or use a cached routing decision. If it fails, report the failing diagnostic and sanitized error; do not invent a successful response or silently change the provider endpoint.",
    "",
    "## 6. Route a sample task and inspect the record",
    "",
    "After check succeeds, and with the user's permission for another routing request and a local record, run:",
    "",
    "```bash",
    'jevia route --json "fix a typo in the README"',
    "jevia runs --json",
    "jevia cache status",
    "```",
    "",
    "Confirm the routing JSON contains a run ID, selected tier, and confidence; find that run in the local history. Report whether a fallback was applied. Routing chooses a tier; it does not execute the coding task or prove that the task succeeded. Do not record success feedback just because routing or installation worked.",
    "",
    "## 7. Report what was verified",
    "",
    "Summarize the installed Jevia version, project/config location, doctor and check exit results, the observed readiness message, and the sample run ID/tier if that step was authorized. Never include credentials. Separate completed checks from skipped or blocked steps and give the next action for any blocker.",
    "",
    "For optional coding-agent execution, configure a harness and its verification command before using `jevia run`; ask which harness and models the user wants rather than guessing. Documentation and examples: https://github.com/assistant-ui/jevia#harness-adapters.",
    "",
  ].join("\n");
}
